prevent_proxy_connections: false
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - Main
  bind_local_address: true
  host: 0.0.0.0:25570
  max_players: 100
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  MoWobbler:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: acca7ccc-c9dd-4eba-a0ca-4e78f44ad55d
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  Main:
    motd: '&1build.simpvp.net'
    address: 127.0.0.25:25575
    restricted: false
